### ISSUE TITLE
Recipe App Group and Setup

### ISSUE THREAD

**Issue by miguelesco** [miguelesco/recipe_app#13]
In this activity, our team prepared a Kanban board with a GitHub project. This time there is not template to copy. We create a Kanban board from scratch. Project requirements are separate tasks and they have a card for each task.

Links
- [Kanbard Board](https://github.com/miguelesco/recipe_app/projects/1)
- [Projects requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md)

Team group
- @Richie9000 
- @miguelesco

**Comment by Dipeshtwis** [comment]
# Status: Approved ✔️

## Hi @miguelesco & @Richie9000,

Good job on implementing all the requirements. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
